#! /bin/sh

[ -f ./shifu ] && . ./shifu || { echo "shifu source not found"; exit 1; }

# help: this is the command test
# long: this command handles test things
#       yada
#       line
test__() {
  exit 1
}

# help: this is the sub command in the test command
# long: this function handles subbing
#       yada yada
#       more lines
test_sub__() {
  echo 1
}

# help: this is a function in the test sub subcommand
# long: this function handles functioning
#       yada yada
#       more lines
test_sub_func() {
  echo test_sub_func "$#" "$@"
}

# help: this is another function in the test sub subcommand
# long: this function handles functioning
#       yada yada
#       more lines
test_sub_function() {
  echo test_sub_function "$#" "$@"
}

# help: this is the subcommand other
# long: this subcommand handles other things
#       yada yada yada
#       more lines yay
other__() {
  exit 1
}

# help: this is the subcommand other stuff
# long: this subcommand handles other things and stuff
#       yada yada yada
#       more lines yay
other_stuff() {
  echo other_stuff "$#" "$@"
}

# help: this is the missing function in the subcommand subcommand
# long: this function handles being an example undiscoverable
#       yada yada yada yada
#       more lines and such
subcommand_missing() {
  exit 0
}

shifu_run "$@"
