#! /bin/sh

# Copyright (c) Cary Goltermann, MIT License
# https://github.com/Ultramann/shifu

# config
shifu_allow_options_anywhere=false
shifu_complete_single_dash_options=false
shifu_help_flags="-h --help"

# modes
shifu_mode_cmds_run=1
shifu_mode_args_run=2
shifu_mode_help_run=3
shifu_mode_help_subs=4
shifu_mode_cmds_comp=5
shifu_mode_args_comp=6
shifu_mode_opt_names_comp=7

_shifu_setup() {
  _shifu_validate_help_flags
  _shifu_help_case_pattern
  _shifu_help_display_flags
}

# api
shifu_run() {
  _shifu_setup
  case $# in
    0) echo "shifu_run requires at least one argument, got 0"
       exit 1 ;;
    1) _shifu_run "$@" ;;
    *) case "$2" in
        --tab-completion) _shifu_generate_tab_completion "$@" ;;
        --shifu-complete) _shifu_complete "$@" ;;
        *) _shifu_run "$@" ;;
       esac ;;
  esac
}

shifu_cmd_name() {
  [ $# -ne 1 ] && _shifu_error "Commands cannot contain spaces got: \"$@\""
  [ ${shifu_mode:-0} -ne $shifu_mode_args_run ] && shifu_cmd_name="$1"
}

shifu_cmd_help() {
  [ ${shifu_mode:-0} -ne $shifu_mode_args_run ] && shifu_cmd_help="$@"
}

shifu_cmd_long() {
  [ ${shifu_mode:-0} -ne $shifu_mode_args_run ] && shifu_cmd_long="$@"
}

shifu_cmd_subs() {
  [ ${shifu_mode:-0} -ne $shifu_mode_args_run ] && shifu_cmd_subs="$@"
}

shifu_cmd_func() {
  [ ${shifu_mode:-0} -ne $shifu_mode_args_run ] && shifu_cmd_func="$@"
}

shifu_cmd_optb() {
  _shifu_cmd_opt_dispatch _shifu_cmd_optb "$@"
}

shifu_cmd_optd() {
  _shifu_cmd_opt_dispatch _shifu_cmd_optd "$@"
}

shifu_cmd_optr() {
  _shifu_cmd_opt_dispatch _shifu_cmd_optr "$@"
}

shifu_cmd_argr() {
  _shifu_cmd_arg_dispatch _shifu_cmd_argr "$@"
}

shifu_cmd_args() {
  _shifu_cmd_arg_dispatch _shifu_cmd_args "$@"
}

shifu_cmd_cpte() {
  [ ${shifu_mode:-0} -ne $shifu_mode_args_comp ] && return
  [ "$shifu_arg_completion_set" = true ] && _shifu_error "Can only add one completion per argument"
  if [ "$shifu_last_arg_is_eager" = true ]; then
    _shifu_append_on_new_line shifu_case_stmt '    [ \$# -ne 0 ] && shift'
    shifu_case_stmt="$shifu_case_stmt || { shifu_add_cpts $@; break; }"
    [ ${shifu_parse_stage:-0} -ne 0 ] && shifu_tmp=";" || shifu_tmp=" ;;"
    shifu_case_stmt="$shifu_case_stmt$shifu_tmp"
  else
    shifu_defer_comp_case="${shifu_defer_comp_case:-}
    [ \$# -ne 0 ] && shift || { shifu_add_cpts $@; break; } ;;"
  fi
  shifu_arg_completion_set=true
}

shifu_cmd_cptf() {
  [ ${shifu_mode:-0} -ne $shifu_mode_args_comp ] && return
  [ "$shifu_arg_completion_set" = true ] && _shifu_error "Can only add one completion per argument"
  if [ "$shifu_last_arg_is_eager" = true ]; then
    _shifu_append_on_new_line shifu_case_stmt '    [ \$# -ne 0 ] && shift'
    shifu_case_stmt="$shifu_case_stmt || { $1; break; }"
    [ ${shifu_parse_stage:-0} -eq 0 ] && shifu_tmp=" ;;" || shifu_tmp=";"
    shifu_case_stmt="$shifu_case_stmt$shifu_tmp"
  else
    shifu_defer_comp_case="${shifu_defer_comp_case:-}
    [ \$# -ne 0 ] && shift || { $1; break; } ;;"
  fi
  shifu_arg_completion_set=true
}

shifu_cmd_cptp() {
  [ ${shifu_mode:-0} -ne $shifu_mode_args_comp ] && return
  [ "$shifu_arg_completion_set" = true ] && _shifu_error "Can only add one completion per argument"
  case ${1:-} in
    :files:) shifu_tmp_sentinel=SHIFU_COMP_PATH_FILES ;;
    :dirs:)  shifu_tmp_sentinel=SHIFU_COMP_PATH_DIRS ;;
    :glob:)  [ -z "${2:-}" ] && return; shifu_tmp_sentinel="SHIFU_COMP_PATH_GLOB:$2" ;;
    *) return ;;
  esac
  if [ "$shifu_last_arg_is_eager" = true ]; then
    _shifu_append_on_new_line shifu_case_stmt '    [ \$# -ne 0 ] && shift'
    shifu_case_stmt="$shifu_case_stmt || { shifu_add_cpts \"$shifu_tmp_sentinel\"; break; }"
    [ ${shifu_parse_stage:-0} -ne 0 ] && shifu_tmp=";" || shifu_tmp=" ;;"
    shifu_case_stmt="$shifu_case_stmt$shifu_tmp"
  else
    shifu_defer_comp_case="${shifu_defer_comp_case:-}
    [ \$# -ne 0 ] && shift || { shifu_add_cpts \"$shifu_tmp_sentinel\"; break; } ;;"
  fi
  shifu_arg_completion_set=true
}

shifu_add_cpts() {
  for completion in "$@"; do
    _shifu_list_append shifu_completions "$completion"
  done
}

shifu_less() {
  cmd_name() { shifu_cmd_name "$@"; }
  cmd_help() { shifu_cmd_help "$@"; }
  cmd_long() { shifu_cmd_long "$@"; }
  cmd_subs() { shifu_cmd_subs "$@"; }
  cmd_func() { shifu_cmd_func "$@"; }
  cmd_optb() { shifu_cmd_optb "$@"; }
  cmd_optd() { shifu_cmd_optd "$@"; }
  cmd_optr() { shifu_cmd_optr "$@"; }
  cmd_argr() { shifu_cmd_argr "$@"; }
  cmd_args() { shifu_cmd_args "$@"; }
  cmd_cpte() { shifu_cmd_cpte "$@"; }
  cmd_cptf() { shifu_cmd_cptf "$@"; }
  cmd_cptp() { shifu_cmd_cptp "$@"; }
  add_cpts() { shifu_add_cpts "$@"; }
}

# helpers
_shifu_run() {
  [ "${SHIFU_SET_X:-0}" = 1 ] && set -x
  shifu_mode=$shifu_mode_cmds_run
  shifu_parent="$1"; shifu_cmd="$1"; shift
  shifu_required_variables=""
  "$shifu_parent"
  _shifu_set_for_looping shifu_cmds shifu_cmd_subs
  while [ $# -ne 0 -a -n "${shifu_cmd_subs:-}" ]; do
    _shifu_parse_args true "$shifu_parent" "$@"
    shifu_mode=$shifu_mode_cmds_run
    shift $_shifu_args_parsed
    shifu_arg_matched=''
    for shifu_cmd in $shifu_cmds; do
      _shifu_clear_cmd_vars
      "$shifu_cmd"
      [ "$1" != "$shifu_cmd_name" ] && continue
      shifu_arg_matched=true; shift
      [ -n "$shifu_cmd_func" ] && break
      shifu_parent="$shifu_cmd"
      _shifu_set_for_looping shifu_cmds shifu_cmd_subs
      break
    done
    [ "$shifu_arg_matched" = true -a -n "$shifu_cmd_func" ] && break
    [ "$shifu_arg_matched" = true -a -n "$shifu_cmd_subs" ] && continue
    if [ -n "${shifu_help_pattern:-}" ]; then
      eval "case \"\$1\" in $shifu_help_pattern) ;; *) echo \"Unknown command: \$1\" ;; esac"
    else
      echo "Unknown command: $1"
    fi
    _shifu_help "$shifu_parent" 1
  done
  [ -z "$shifu_cmd_func" ] && { echo "$shifu_cmd_name requires arguments"; _shifu_help "$shifu_cmd" 1; }
  if [ -n "${shifu_help_pattern:-}" ]; then
    eval "case \"\${1:-}\" in $shifu_help_pattern) _shifu_help \"\$shifu_cmd\" 0 ;; esac"
  fi
  _shifu_parse_args false "$shifu_cmd" "$@"
  [ $? -ne 0 ] && _shifu_help "$shifu_cmd" 1
  shift $_shifu_args_parsed
  [ "${SHIFU_SET_X:-0}" = 1 ] && set +x
  "$shifu_cmd_func" "$@"
}

_shifu_parse_args() {
  shifu_mode=$shifu_mode_args_run
  shifu_parse_stage=0
  shifu_parse_eager="$1"; shifu_cmd="$2"; shift 2
  [ "$shifu_parse_eager" = true ] && shifu_required_variables_eager=""
  shifu_required_positionals=""
  shifu_case_stmt="case \"\$1\" in"
  if [ "$shifu_parse_eager" = false -a -n "${shifu_defer_case:-}" ]; then
    _shifu_append_on_new_line shifu_case_stmt "  ${shifu_defer_case:-}"
  fi
  [ -n "${shifu_help_pattern:-}" ] && \
    _shifu_append_on_new_line shifu_case_stmt "  $shifu_help_pattern) _shifu_help \"$shifu_cmd\" 0 ;; "
  "$shifu_cmd"
  [ $shifu_parse_stage -eq 0 ] && _shifu_update_case_stmt_invalid_option
  _shifu_append_on_new_line shifu_case_stmt "    break;;"
  _shifu_append_on_new_line shifu_case_stmt "esac"
  _shifu_args_parsed=0
  _shifu_n_args=$#
  while [ $# -ne 0 ]; do
    eval "$shifu_case_stmt" || _shifu_case_eval_error
    [ $# -eq $_shifu_n_args ] && _shifu_case_loop_error
    _shifu_n_args=$#
  done
  if [ "$shifu_parse_eager" = true ]; then
    _shifu_set_for_looping shifu_req_variables shifu_required_variables_eager
  else
    _shifu_set_for_looping shifu_req_variables shifu_required_variables
  fi
  for shifu_req_variables in $shifu_req_variables; do
    eval "if [ \"\${$shifu_req_variables+set}\" != set ]; then
      echo \"Required variable, $shifu_req_variables, is not set\"
      _shifu_help \"$shifu_cmd\" 1
    fi"
  done
  _shifu_set_for_looping shifu_req_positionals shifu_required_positionals
  for shifu_req_positional in $shifu_req_positionals; do
    eval "if [ -z \"\${$shifu_req_positional}\" ]; then
      echo \"Missing positional argument $shifu_req_positional\"
      _shifu_help \"$shifu_cmd\" 1
    fi"
  done
  [ "$shifu_parse_eager" = true -o $# -eq 0 -o "$shifu_allow_options_anywhere" != false ] && return
  _shifu_error_if_options "$@"
}

_shifu_ack_arg() {
  _shifu_args_parsed=$((_shifu_args_parsed + ${1:-1}))
}

_shifu_clear_cmd_vars() {
    shifu_cmd_name='' shifu_cmd_help='' shifu_cmd_long='' shifu_cmd_subs='' shifu_cmd_func=''
}

_shifu_help() {
  shifu_mode=$shifu_mode_cmds_run
  _shifu_clear_cmd_vars
  "$1"
  _shifu_make_subcmd_help
  shifu_mode=$shifu_mode_help_run
  _shifu_clear_cmd_vars
  shifu_help_stage=0
  "$1"
  [ -n "$shifu_cmd_func" ] && shifu_help_options="${shifu_help_options:-}${shifu_defer_help:-}"
  [ -n "${shifu_help_display:-}" ] && \
    shifu_help_options="${shifu_help_options:-}\n  $shifu_help_display\n    Show this help"
  [ -n "${shifu_help_usage:-}" ] && shifu_help_usage="$shifu_cmd_name [OPTIONS]$shifu_help_usage"
  [ -n "$shifu_cmd_help" ] && _shifu_add_to_help_string "$shifu_cmd_help"
  [ -n "$shifu_cmd_long" ] && _shifu_add_to_help_string "$shifu_cmd_long"
  [ -n "${shifu_help_usage:-}" ] && _shifu_add_to_help_string "Usage\n  $shifu_help_usage"
  [ -n "${shifu_help_arguments:-}" ] && _shifu_add_to_help_string "Arguments$shifu_help_arguments"
  [ -n "${shifu_subcmd_help:-}" ] && _shifu_add_to_help_string "Subcommands$shifu_subcmd_help"
  [ -n "$shifu_help_options" ] && _shifu_add_to_help_string "Options$shifu_help_options"
  [ -n "$shifu_help_string" ] && printf "$shifu_help_string\n"
  exit $2
}

_shifu_add_to_help_string() {
  shifu_help_string="${shifu_help_string:-}${shifu_help_string:+\n\n}$1"
}

_shifu_make_subcmd_help() {
  shifu_mode=$shifu_mode_help_subs
  [ -z "${shifu_cmd_subs:-}" ] && return
  _shifu_set_for_looping shifu_subcmds shifu_cmd_subs
  _shifu_clear_cmd_vars
  for shifu_subcmd in $shifu_subcmds; do
    shifu_help_stage=0
    "$shifu_subcmd"
    shifu_subcmd_help="${shifu_subcmd_help:-}\n  $shifu_cmd_name"
    [ -n "${shifu_cmd_help:-}" ] && shifu_subcmd_help="${shifu_subcmd_help:-}\n    $shifu_cmd_help"
  done
}

_shifu_opt_build() {
  shifu_build_var="$1"
  shifu_build_prefix="$2"
  shifu_build_sep="$3"
  shift 3
  _shifu_validate_flag "$1"
  eval "$shifu_build_var=\"\${$shifu_build_var:-}$shifu_build_prefix\$1\""
  shifu_opt_count=2
  shift
  while [ $# -gt 0 ] && [ "$1" != -- ]; do
    _shifu_validate_flag "$1"
    eval "$shifu_build_var=\"\$$shifu_build_var$shifu_build_sep\$1\""
    shifu_opt_count=$((shifu_opt_count + 1))
    shift
  done
}

_shifu_add_equals_case_arms() {
  shifu_eq_target="$1"; shifu_eq_var="$2"
  _shifu_set_for_looping shifu_eq_list shifu_eq_saved_args
  for shifu_eq_flag in $shifu_eq_list; do
    case "$shifu_eq_flag" in
      --) break ;;
      --*) _shifu_append_on_new_line "$shifu_eq_target" \
             "  $shifu_eq_flag=*) $shifu_eq_var=\\\${1#*=}; shift; _shifu_ack_arg ;;" ;;
    esac
  done
}

_shifu_add_equals_defer_case_arms() {
  shifu_eq_var="$1"
  _shifu_set_for_looping shifu_eq_list shifu_eq_saved_args
  for shifu_eq_flag in $shifu_eq_list; do
    case "$shifu_eq_flag" in
      --) break ;;
      --*) shifu_defer_case="$shifu_defer_case
  $shifu_eq_flag=*) $shifu_eq_var=\\\${1#*=}; shift; _shifu_ack_arg ;;" ;;
    esac
  done
}

_shifu_add_comp_eq_patterns() {
  if [ -n "${shifu_comp_eq_patterns:-}" ]; then
    shifu_case_stmt="${shifu_case_stmt}${shifu_comp_eq_patterns}"
    shifu_comp_eq_patterns=""
  fi
}

_shifu_add_equals_comp_case_arms() {
  shifu_eq_target="$1"
  _shifu_set_for_looping shifu_eq_list shifu_eq_saved_args
  for shifu_eq_flag in $shifu_eq_list; do
    case "$shifu_eq_flag" in
      --) break ;;
      --*) _shifu_append_on_new_line "$shifu_eq_target" "  $shifu_eq_flag=*) shift ;;" ;;
    esac
  done
}

_shifu_validate_flag() {
  case "$1" in
    -*) ;;
    *) _shifu_error "Option flags must start with - or --, got: $1" ;;
  esac
}

_shifu_validate_help_flags() {
  _shifu_set_for_looping shifu_help_flags_list shifu_help_flags
  for shifu_help_flag in $shifu_help_flags_list; do
    _shifu_validate_flag "$shifu_help_flag"
    case "$shifu_help_flag" in
      *'?'*|*'*'*|*'['*) _shifu_error "Help flag contains glob character: $shifu_help_flag" ;;
    esac
  done
}

_shifu_help_case_pattern() {
  shifu_help_pattern=""
  _shifu_set_for_looping shifu_help_flags_list shifu_help_flags
  for shifu_help_flag in $shifu_help_flags_list; do
    shifu_help_pattern="${shifu_help_pattern:+$shifu_help_pattern|}$shifu_help_flag"
  done
}

_shifu_help_display_flags() {
  shifu_help_display=""
  _shifu_set_for_looping shifu_help_flags_list shifu_help_flags
  for shifu_help_flag in $shifu_help_flags_list; do
    shifu_help_display="${shifu_help_display:+$shifu_help_display, }$shifu_help_flag"
  done
}

_shifu_opt_help_parse() {
  _shifu_opt_build shifu_help_options '\n  ' ', ' "$@"
}

_shifu_opt_case_parse() {
  _shifu_opt_build shifu_case_stmt '
  ' '|' "$@"
}

_shifu_opt_defer_parse() {
  _shifu_opt_build shifu_defer_case '' '|' "$@"
  _shifu_opt_build shifu_defer_help '\n  ' ', ' "$@"
}

_shifu_opt_comp_preamble() {
  if [ "$shifu_arg_completion_set" = false ] && [ $shifu_parse_stage -eq 0 ]; then
    shifu_case_stmt="$shifu_case_stmt shift ;;"
  fi
  shifu_arg_completion_set=false
  shifu_last_arg_is_eager=true
}

_shifu_opt_comp_eager_parse() {
  _shifu_opt_comp_preamble
  _shifu_collect_option_names "$@"
  _shifu_opt_case_parse "$@"
}

_shifu_opt_build_comp_defer_parse() {
  shifu_arg_completion_set=false
  shifu_last_arg_is_eager=false
  _shifu_collect_option_names "$@"
  _shifu_opt_build shifu_defer_comp_case '
  ' '|' "$@"
}

_shifu_cmd_optb_help() {
  _shifu_opt_help_parse "$@"
  shift $shifu_opt_count
  _shifu_error_if_invalid_arg_order "$1" $shifu_help_stage
  shifu_help_options="$shifu_help_options\n    $4\n    Default: ${2:-empty}, set: $3"
}

_shifu_cmd_optb_build_now() {
  _shifu_opt_case_parse "$@"
  shift $shifu_opt_count
  _shifu_error_if_invalid_arg_order "$1" $shifu_parse_stage
  _shifu_set_variable "$1" "$2"
  shifu_case_stmt="$shifu_case_stmt) $1=$3; shift; _shifu_ack_arg ;;"
}

_shifu_cmd_optb_build_defer() {
  _shifu_opt_defer_parse "$@"
  shift $shifu_opt_count
  _shifu_set_variable "$1" "$2"
  shifu_defer_case="${shifu_defer_case:-}) $1=$3; shift; _shifu_ack_arg ;;"
  shifu_defer_help="${shifu_defer_help:-}\n    $4\n    Default: $2, set: $3"
}

_shifu_cmd_optb_build_comp_now() {
  _shifu_opt_comp_eager_parse "$@"
  shift $shifu_opt_count
  _shifu_error_if_invalid_arg_order "$1" $shifu_parse_stage
  shifu_case_stmt="$shifu_case_stmt)"
}

_shifu_cmd_optb_build_comp_defer() {
  _shifu_opt_build_comp_defer_parse "$@"
  shift $shifu_opt_count
  shifu_defer_comp_case="${shifu_defer_comp_case:-}) shift ;;"
}

_shifu_cmd_optd_help() {
  _shifu_opt_help_parse "$@"
  shift $shifu_opt_count
  _shifu_error_if_invalid_arg_order "$1" $shifu_help_stage
  shifu_help_options="$shifu_help_options [$1]\n    $3\n    Default: $2"
}

_shifu_cmd_optd_build_now() {
  shifu_eq_saved_args="$*"
  _shifu_opt_case_parse "$@"
  shift $shifu_opt_count
  _shifu_error_if_invalid_arg_order "$1" $shifu_parse_stage
  _shifu_set_variable "$1" "$2"
  _shifu_update_case_stmt_option_value_check
  shifu_case_stmt="$shifu_case_stmt $1=\$2; shift 2; _shifu_ack_arg 2 ;;"
  _shifu_add_equals_case_arms shifu_case_stmt "$1"
}

_shifu_cmd_optd_build_defer() {
  shifu_eq_saved_args="$*"
  _shifu_opt_defer_parse "$@"
  shift $shifu_opt_count
  _shifu_set_variable "$1" "$2"
  _shifu_update_case_stmt_option_value_check defer
  shifu_defer_case="$shifu_defer_case $1=\\\$2; shift 2; _shifu_ack_arg 2 ;;"
  shifu_defer_help="${shifu_defer_help:-} [$1]\n    $3\n    Default: $2"
  _shifu_add_equals_defer_case_arms "$1"
}

_shifu_cmd_optv_build_comp_now() {
  shifu_eq_saved_args="$*"
  _shifu_opt_comp_eager_parse "$@"
  shift $shifu_opt_count
  _shifu_error_if_invalid_arg_order "$1" $shifu_parse_stage
  shifu_case_stmt="$shifu_case_stmt) shift;"
  _shifu_add_equals_comp_case_arms shifu_comp_eq_patterns
}

_shifu_cmd_optv_build_comp_defer() {
  shifu_eq_saved_args="$*"
  _shifu_opt_build_comp_defer_parse "$@"
  shift $shifu_opt_count
  shifu_defer_comp_case="${shifu_defer_comp_case:-}) shift;"
  _shifu_add_equals_comp_case_arms shifu_comp_eq_patterns
}

_shifu_cmd_optr_help() {
  _shifu_opt_help_parse "$@"
  shift $shifu_opt_count
  _shifu_error_if_invalid_arg_order "$1" $shifu_help_stage
  shifu_help_options="$shifu_help_options $1\n    $2\n    Required"
}

_shifu_cmd_optr_build_now() {
  shifu_eq_saved_args="$*"
  _shifu_opt_case_parse "$@"
  shift $shifu_opt_count
  _shifu_error_if_invalid_arg_order "$1" $shifu_parse_stage
  _shifu_list_append shifu_required_variables "$1"
  _shifu_update_case_stmt_option_value_check
  shifu_case_stmt="$shifu_case_stmt $1=\$2; shift 2; _shifu_ack_arg 2 ;;"
  _shifu_add_equals_case_arms shifu_case_stmt "$1"
}

_shifu_cmd_optr_build_defer() {
  shifu_eq_saved_args="$*"
  _shifu_opt_defer_parse "$@"
  shift $shifu_opt_count
  _shifu_list_append shifu_required_variables "$1"
  _shifu_update_case_stmt_option_value_check defer
  shifu_defer_case="$shifu_defer_case $1=\\\$2; shift 2; _shifu_ack_arg 2 ;;"
  shifu_defer_help="${shifu_defer_help:-} $1\n    $2\n    Required"
  _shifu_add_equals_defer_case_arms "$1"
}

_shifu_cmd_optd_build_comp_now() { _shifu_cmd_optv_build_comp_now "$@"; }
_shifu_cmd_optd_build_comp_defer() { _shifu_cmd_optv_build_comp_defer "$@"; }
_shifu_cmd_optr_build_comp_now() { _shifu_cmd_optv_build_comp_now "$@"; }
_shifu_cmd_optr_build_comp_defer() { _shifu_cmd_optv_build_comp_defer "$@"; }

_shifu_cmd_argr_help() {
  if [ $shifu_help_stage -lt 1 ]; then
    shifu_help_stage=1
  elif [ $shifu_help_stage -gt 1 ]; then
    _shifu_error "No arguments after remaining are declared: $1"
  fi
  shifu_help_usage="${shifu_help_usage:-} [$1]"
  shifu_help_arguments="${shifu_help_arguments:-}\n  $1\n    $2"
}

_shifu_cmd_argr_build_now() {
  if [ $shifu_parse_stage -eq 0 ]; then
    shifu_parse_stage=1
    _shifu_update_case_stmt_invalid_option
  elif [ $shifu_parse_stage -gt 1 ]; then
    _shifu_error "No arguments after remaining are declared: $1"
  fi
  _shifu_set_variable "$1" ""
  _shifu_list_append shifu_required_positionals "$1"
  _shifu_append_on_new_line shifu_case_stmt "    $1=\\\$1; shift; _shifu_ack_arg"
}

_shifu_cmd_argr_build_comp_now() {
  _shifu_opt_comp_preamble
  if [ $shifu_parse_stage -eq 0 ]; then
    shifu_parse_stage=1
    _shifu_add_comp_eq_patterns
    _shifu_append_on_new_line shifu_case_stmt "  *)"
  elif [ $shifu_parse_stage -gt 1 ]; then
    _shifu_error "No arguments after remaining are declared: $1"
  fi
}

_shifu_cmd_args_help() {
  shifu_help_stage=2
  shifu_help_usage="$shifu_help_usage ...[REMAINING]"
  shifu_help_arguments="$shifu_help_arguments\n  REMAINING\n    $1"
}

_shifu_cmd_args_build_now() {
  [ $shifu_parse_stage -gt 1 ] && _shifu_error "Can only declare remaining arguments once: $1"
  [ $shifu_parse_stage -eq 0 ] && _shifu_update_case_stmt_invalid_option
  shifu_parse_stage=2
}

_shifu_cmd_args_build_comp_now() {
  _shifu_opt_comp_preamble
  [ $shifu_parse_stage -eq 2 ] && _shifu_error "Can only declare remaining arguments once: $1"
  [ $shifu_parse_stage -eq 0 ] && _shifu_add_comp_eq_patterns
  shifu_parse_stage=2
}

_shifu_cmd_opt_dispatch() {
  shifu_dispatch_prefix="$1"; shift
  if [ -n "${shifu_cmd_func:-}" ]; then
    shifu_arg_scope=eager
  elif [ "$1" = ":eager:" ]; then
    shifu_arg_scope=eager; shift
  elif [ "$1" = ":defer:" ]; then
    shifu_arg_scope=defer; shift
  else
    _shifu_error "Mode :eager: or :defer: required in non-leaf commands"
  fi
  case ${shifu_mode:-0} in
    $shifu_mode_help_run) "${shifu_dispatch_prefix}_help" "$@" ;;
    $shifu_mode_args_run)
      if [ "$shifu_arg_scope" = eager ]; then "${shifu_dispatch_prefix}_build_now" "$@"
      else "${shifu_dispatch_prefix}_build_defer" "$@"; fi ;;
    $shifu_mode_args_comp)
      if [ "$shifu_arg_scope" = eager ]; then "${shifu_dispatch_prefix}_build_comp_now" "$@"
      else "${shifu_dispatch_prefix}_build_comp_defer" "$@"; fi ;;
    $shifu_mode_opt_names_comp) _shifu_collect_option_names "$@" ;;
  esac
}

_shifu_cmd_arg_dispatch() {
  shifu_dispatch_prefix="$1"; shift
  [ -n "${shifu_cmd_func:-}" ] || _shifu_error "Positional arguments can only be used in leaf commands"
  case ${shifu_mode:-0} in
    $shifu_mode_help_run) "${shifu_dispatch_prefix}_help" "$@" ;;
    $shifu_mode_args_run) "${shifu_dispatch_prefix}_build_now" "$@" ;;
    $shifu_mode_args_comp) "${shifu_dispatch_prefix}_build_comp_now" "$@" ;;
  esac
}

_shifu_generate_tab_completion() {
  shifu_mode=$shifu_mode_cmds_run
  "$1"
  case "$3" in
    zsh) _shifu_generate_zsh_tab_completion "$@";;
    bash) _shifu_generate_bash_tab_completion "$@";;
    help) _shifu_tab_completion_help ;;
    *) echo "Unknown shell, $3, cannot perform tab completion"; exit 1 ;;
  esac
}

_shifu_tab_completion_help() {
  echo "Generate tab completion code for specified shell

Instructions
1. Ensure $shifu_cmd_name is in a directory on your shell's PATH
2. Ensure $shifu_cmd_name has access to shifu; either by putting
   shifu in the same PATH directory as $shifu_cmd_name or adding
   shifu to another PATH directory
3. If you're using zsh, ensure that you've loaded and run
   compinit before the following eval call in your zshrc file
4. Add the following to your shell's rc file
     eval \"\$($shifu_cmd_name --tab-completion <shell>)\"
   replacing <shell> with your shell. Supported shells:
     bash, zsh"
}

_shifu_generate_bash_tab_completion() {
  echo "_${shifu_cmd_name}_completion() {
  current=\"\${COMP_WORDS[\${#COMP_WORDS[@]}-1]}\"
  comp_current=\"\$current\"
  case \"\$current\" in
    -*=*) comp_current=\"\${current#*=}\" ;;
  esac
  full_words=( \"\${COMP_WORDS[@]:1:\${#COMP_WORDS[@]}-2}\" )
  completions=\$($shifu_cmd_name --shifu-complete \"\$current\" \"\${full_words[@]}\")
  case \"\$completions\" in
    SHIFU_COMP_PATH_FILES) COMPREPLY=( \$(compgen -f -- \"\$comp_current\") ) ;;
    SHIFU_COMP_PATH_DIRS) COMPREPLY=( \$(compgen -d -- \"\$comp_current\") ) ;;
    SHIFU_COMP_PATH_GLOB:*) COMPREPLY=( \$(compgen -f -X \"!\${completions#SHIFU_COMP_PATH_GLOB:}\" -- \"\$comp_current\") ) ;;
    *) COMPREPLY=( \$(compgen -W \"\$completions\" -- \"\$comp_current\") )
       compopt +o filenames 2>/dev/null ;;
  esac
}
complete -o filenames -F _${shifu_cmd_name}_completion $shifu_cmd_name"
}

_shifu_generate_zsh_tab_completion() {
  echo "_${shifu_cmd_name}_completion() {
  current=\"\${words[\$CURRENT]}\"
  full_words=( \"\${words[@]:1:\${#words[@]}-2}\" )
  completions=\$($shifu_cmd_name --shifu-complete \"\$current\" \"\${full_words[@]}\")
  case \"\$current\" in
    -*=*) IPREFIX=\"\${current%%=*}=\"; PREFIX=\"\${current#*=}\" ;;
  esac
  case \"\$completions\" in
    SHIFU_COMP_PATH_FILES) _files -g '*(D)' ;;
    SHIFU_COMP_PATH_DIRS) _files -g '*(D/)' ;;
    SHIFU_COMP_PATH_GLOB:*) _path_files -g \"\${completions#SHIFU_COMP_PATH_GLOB:}\" ;;
    *) compadd -q -- \${=completions} ;;
  esac
}
compdef _${shifu_cmd_name}_completion $shifu_cmd_name"
}

_shifu_complete() {
  shifu_mode=$shifu_mode_cmds_comp
  shifu_parent="$1"; shifu_cmd="$1"; shifu_current_word="$3"; shift 3
  # current word is only non-empty if there are ascii chars after the last full word
  "$shifu_parent"
  _shifu_set_for_looping shifu_cmds shifu_cmd_subs
  while [ $# -ne 0 -a -n "${shifu_cmd_subs:-}" ]; do
    _shifu_complete_func_args true "$shifu_parent" "$@" || _shifu_args_parsed=0
    shift $_shifu_args_parsed
    [ $# -eq 0 ] && break
    shifu_build_comp_defer_option_names="${shifu_comp_option_names:-}"
    shifu_mode=$shifu_mode_cmds_comp
    shifu_arg_matched=''
    for shifu_cmd in $shifu_cmds; do
      _shifu_clear_cmd_vars
      "$shifu_cmd"
      [ "$1" != "$shifu_cmd_name" ] && continue
      shifu_arg_matched=true; shift
      [ -n "$shifu_cmd_func" ] && break
      shifu_parent="$shifu_cmd"
      _shifu_set_for_looping shifu_cmds shifu_cmd_subs
      break
    done
    [ "$shifu_arg_matched" != true ] && _shifu_clear_cmd_vars
    [ "$shifu_arg_matched" = true -a -n "$shifu_cmd_subs" ] && continue
    break
  done
  shifu_comp_option_names="${shifu_build_comp_defer_option_names:-}"
  _shifu_set_completing_option
  case "${shifu_current_word:-}" in
    -*=*) set -- "$@" "${shifu_current_word%%=*}" ;;
  esac
  [ "$shifu_completing_option" = true ] && shifu_completions=""
  if [ "$shifu_completing_option" = true -a -n "${shifu_cmd_func:-}" ]; then
    _shifu_complete_option_names
  elif [ "$shifu_completing_option" = true -a -n "${shifu_cmd_subs:-}" ]; then
    shifu_comp_option_names=""
    _shifu_complete_option_names
  elif [ "$shifu_completing_option" = false -a -n "${shifu_cmd_func:-}" ]; then
    _shifu_complete_func_args false "$shifu_cmd" "$@"
  elif [ "$shifu_completing_option" = false -a -n "${shifu_cmd_subs:-}" -a $# -eq 0 -a -z "${shifu_completions:-}" ]; then
    _shifu_complete_subcmd_names
  fi
  [ -n "${shifu_completions:-}" ] && echo "$shifu_completions"
}

_shifu_set_completing_option() {
  case "${shifu_current_word:-}" in
    -*=*) shifu_completing_option=false ;;
    -*) shifu_completing_option=true ;;
    *) shifu_completing_option=false ;;
  esac
}

_shifu_complete_option_names() {
  shifu_mode=$shifu_mode_opt_names_comp
  "$shifu_cmd"
  _shifu_set_for_looping shifu_complete_help_flags shifu_help_flags
  for shifu_help_flag in $shifu_complete_help_flags; do
    _shifu_list_append shifu_comp_option_names "$shifu_help_flag"
  done
  _shifu_set_for_looping shifu_comp_option_list shifu_comp_option_names
  _shifu_filter_matching_options "$shifu_current_word" $shifu_comp_option_list
}

_shifu_collect_option_names() {
  [ "$1" = -- ] && return
  _shifu_list_append shifu_comp_option_names "$1"
  shift
  while [ $# -gt 1 -a "$1" != -- ]; do
    shifu_comp_option_names="$shifu_comp_option_names $1"
    shift
  done
}

_shifu_complete_subcmd_names() {
  "$shifu_parent"
  _shifu_set_for_looping shifu_cmds shifu_cmd_subs
  for shifu_cmd in $shifu_cmds; do
    "$shifu_cmd"
    _shifu_list_append shifu_completions "$shifu_cmd_name"
  done
}

_shifu_complete_func_args() {
  shifu_mode=$shifu_mode_args_comp
  shifu_parse_stage=0
  shifu_parse_eager="$1"; shifu_cmd="$2"; shift 2
  _shifu_args_parsed=0
  shifu_comp_eq_patterns=""
  shifu_case_stmt="case \"\${1:-}\" in "
  if [ "$shifu_parse_eager" = false -a -n "${shifu_defer_comp_case:-}" ]; then
    shifu_case_stmt="${shifu_case_stmt}
${shifu_defer_comp_case:-}"
  fi
  shifu_arg_completion_set=true
  shifu_last_arg_is_eager=true
  "$shifu_cmd"
  case "${shifu_current_word:-}" in
    -*=*) ;;
    -*) [ "$shifu_parse_eager" = false ] && return 0 ;;
  esac
  if [ $shifu_parse_stage -eq 0 -a $shifu_arg_completion_set = false ]; then
    shifu_case_stmt="$shifu_case_stmt shift ;;"
  fi
  _shifu_add_comp_eq_patterns
  if [ "$shifu_parse_eager" = true ]; then
    _shifu_append_on_new_line shifu_case_stmt "  *) _shifu_comp_done=true ;;"
  elif [ $shifu_parse_stage -ne 0 ]; then
    _shifu_append_on_new_line shifu_case_stmt "    _shifu_comp_done=true ;;"
  elif [ $shifu_arg_completion_set = true ]; then
    _shifu_append_on_new_line shifu_case_stmt "  *) _shifu_comp_done=true ;;"
  else
    _shifu_append_on_new_line shifu_case_stmt "    _shifu_comp_done=true ;;"
  fi
  _shifu_append_on_new_line shifu_case_stmt "esac"
  _shifu_args_parsed=$#
  _shifu_n_args=$#
  _shifu_comp_done=false
  while [ "$_shifu_comp_done" = false ]; do
    eval "$shifu_case_stmt" 2>/dev/null || return 1
    [ $# -eq $_shifu_n_args ] && _shifu_comp_done=true
    _shifu_n_args=$#
  done
  _shifu_args_parsed=$((_shifu_args_parsed - $#))
}

_shifu_filter_matching_options() {
  shifu_filter_current_word="$1"; shift
  [ "$shifu_complete_single_dash_options" = false ] && \
    [ "$shifu_filter_current_word" = "-" ] && shifu_filter_current_word="--"
  for shifu_filter_option in "$@"; do
    case "$shifu_filter_option" in
      "$shifu_filter_current_word"*)
        _shifu_list_append shifu_completions "$shifu_filter_option" ;;
    esac
  done
}

_shifu_update_case_stmt_invalid_option() {
  shifu_case_stmt="$shifu_case_stmt
  -*) echo \"Invalid option: \$1\"; _shifu_help \"\$shifu_cmd\" 1 ;;
  *)"
}

_shifu_append_on_new_line() {
  eval "$1=\"\$$1
$2\""
}

_shifu_error_if_options() {
  while [ $# -gt 0 ]; do
    case "$1" in
      -*) echo "No options allowed after any positional argument: $1"; return 1 ;;
    esac
    shift
  done
}

_shifu_update_case_stmt_option_value_check() {
  if [ "${1:-}" = "defer" ]; then
    shifu_defer_case="${shifu_defer_case:-}) [ \\\$# -lt 2 ] && { echo \\\"Option \\\$1 requires a value\\\"; _shifu_help \\\"\\\$shifu_cmd\\\" 1; };"
  else
    shifu_case_stmt="$shifu_case_stmt) [ \$# -lt 2 ] && { echo \"Option \$1 requires a value\"; _shifu_help \"\$shifu_cmd\" 1; };"
  fi
}

_shifu_set_for_looping() {
  eval "[ -z \"\${$2:-}\" ] && { $1=''; return; }"
  if [ -n "${ZSH_VERSION:-}" ]; then
    eval "$1=( \${=$2} )"
  else
    eval "$1=\$$2"
  fi
}

_shifu_set_variable() {
  eval "$1=\"$2\"" > /dev/null 2>&1
  [ $? -eq 0 ] && return 0
  _shifu_error "Invalid variable name: $1"
}

_shifu_list_append() {
  eval "$1=\"\${$1:-}\${$1:+ }$2\""
}

_shifu_error_if_invalid_arg_order() {
  [ $2 -eq 0 ] && return
  _shifu_error "No options after positional/remaining arguments: $1"
}

_shifu_error() {
  echo "$1"
  exit 1
}

_shifu_case_loop_error() {
  echo "Internal error"
  [ "${SHIFU_DEBUG_CASE:-0}" = 1 ] && printf '%s\n' "$shifu_case_stmt"
  exit 1
}

_shifu_case_eval_error() {
  echo "Internal error"
  [ "${SHIFU_DEBUG_CASE:-0}" = 1 ] && printf '%s\n' "$shifu_case_stmt"
  exit 1
}

_shifu_trace() {
  if [ $# -eq 1 ]; then
    eval "echo $1: \${$1:-}"
  else
    shifu_trace_name="$1"; shift
    eval "echo $shifu_trace_name: $@"
  fi
}
