#! /bin/sh

# Must be run from repo root with
#    tests/run <args>
# If shifu has a bug that causes this script to not start correctly
# tests can be run manually with
#    <shell> tests/test_shifu.sh <args>

. ./shifu && shifu_less || exit 1

yellow="$(tput setaf 3 2>/dev/null || true)"
reset="$(tput sgr0 2>/dev/null || true)"

run_cmd() {
  cmd_name run
  cmd_func run_tests
  cmd_help "Run shifu tests"

  cmd_arg -v --verbose -- verbose "" -v "Show status for each test, pass or fail"
  cmd_arg -x           -- set_x   "" -x "Set execution tracing for each test"
  cmd_arg -i --image   -- image   ""    "Docker image to run tests in"
  cmd_arg              -- shell "Shell to run tests in. Options: all, ash, bash, dash, ksh, zsh"
  cmd_arg              --         "Specific tests to run"
}

run_tests() {
  shells="ash bash dash ksh zsh"
  if [ -n "$image" ]; then
    podman run --rm -t -v "$(pwd):/shifu" -w /shifu "$image" \
      tests/run $verbose $set_x "$shell" "$@"
  elif [ "$shell" = "all" ]; then
    for s in $shells; do run_tests_in_shell "$s" "$@"; done
  else
    run_tests_in_shell "$shell" "$@"
  fi
  echo
}

run_tests_in_shell() {
  test_shell="$1"; shift
  len=${#test_shell}
  pad=$(( (6 - len) / 2 ))
  printf "\n=========================%*s %-*s ==========================\n" $pad "" $((6 - pad)) "$test_shell"
  if command -v "$test_shell" >/dev/null 2>&1; then
    eval "$test_shell tests/test_shifu.sh $verbose $set_x $@"
  else
    printf "==================== %s Shell not found %s ====================\n" "$yellow" "$reset"
  fi
}

shifu_run run_cmd "$@"
