#! /bin/sh

. "${0%/*}"/shifu && shifu_less || exit 1

dispatch_cmd() {
  cmd_name dispatch
  cmd_subs hello_cmd echo_cmd
  cmd_help "A dispatch shifu example"
  cmd_long "An example shifu cli demonstrating
  * subcommand dispatch
  * argument parsing
  * scoped help generation"

  cmd_optb :defer: -D --deferred -- DEFERRED false true "Deferred binary option"
}

hello_cmd() {
  cmd_name hello
  cmd_func dispatch_hello
  cmd_help "A hello world subcommand"
  cmd_long "A subcommand that prints greeting with arguments"

  cmd_optd -n --name -- NAME "mysterious user" "Name to greet"
}

dispatch_hello() {
  [ "$DEFERRED" = true ] && message="☝ " || message=""
  echo "${message}Hello, $NAME!"
}

echo_cmd() {
  cmd_name echo
  cmd_func dispatch_echo
  cmd_help "An echo subcommand"
  cmd_long "A subcommand that prints results of parsed arguments"

  cmd_optr -r --required -- REQUIRED   "Example required option w/ argument"
  cmd_optd -d --default  -- DEFAULT    "default" "Example option w/ argument"
  cmd_argr                  POSITIONAL "Example positional argument"
}

dispatch_echo() {
  echo "Deferred binary option: $DEFERRED"
  echo "Required option:        $REQUIRED"
  echo "Option w/ default:      $DEFAULT"
  echo "Positional argument:    $POSITIONAL"
}

shifu_run dispatch_cmd "$@"
