#! /bin/sh

. "${0%/*}"/shifu || exit 1

intro_cmd() {
  shifu_cmd_name intro
  shifu_cmd_func intro_function
  shifu_cmd_help "An introduction shifu cli"
  shifu_cmd_long "This command function will invoke intro_function which prints
  an option value provided by '-o' or '--option', defaults to none"
  shifu_cmd_optd -o --option -- OPTION none "Example option to echo"
}

intro_function() {
  echo "$OPTION"
}

shifu_run intro_cmd "$@"
