#! /bin/sh

. "$(dirname "$0")"/shifu && shifu_less || exit 1

kfp_quick_cmd() {
  cmd_name kfp-quick
  cmd_help "An example quickstart to shifu"
  cmd_long "An example shifu cli that provides toy functionality to see different Kung Fu Panda quotes"
  cmd_func kfp_quick

  cmd_arg -l --loud  -- LOUD  false true "Display text loudly!"
  cmd_arg -q --quiet -- QUIET false true 'Display text "quietly"'
  cmd_arg            -- CHARACTER "Select character to see quote: oogway, shifu, po"
}

kfp_quick() {
  parse_args kfp_quick_cmd "$@"

  case "$CHARACTER" in
    oogway) string="One often meets his destiny on the road he takes to avoid it." ;;
    shifu) string="There is now a level zero." ;;
    po) string="I love kung fuuuuuu!!!" ;;
    *) echo "Unknown option $1"; exit 1 ;;
  esac

  [ "$LOUD" = true ] && string=$(echo "$string" | awk '{ print toupper($0) }')
  [ "$QUIET" = true ] && string="$string shhhh!!"
  echo "$string"
}

run_cmd kfp_quick_cmd "$@"
