#! /bin/sh

. "${0%/*}"/shifu less || exit 1

quick_cmd() {
  cmd_name quick
  cmd_subs hello_cmd start_cmd
  cmd_help "A quick shifu example"
  cmd_long "An example shifu cli demonstrating
  * subcommand dispatch
  * argument parsing
  * scoped help generation"

  cmd_arg -g --global -- GLOBAL false true "Global binary option"
}

hello_cmd() {
  cmd_name hello
  cmd_func quick_hello
  cmd_help "A hello world subcommand"
  cmd_long "A subcommand that prints greeting with arguments"

  cmd_arg -n --name -- NAME "mysterious user" "Name to greet"
}

quick_hello() {
  [ "$GLOBAL" = true ] && message="🌐 " || message=""
  echo "${message}Hello, $NAME!"
}

start_cmd() {
  cmd_name start
  cmd_func quick_start
  cmd_help "A quick subcommand"
  cmd_long "A subcommand that prints results of parsed arguments"

  cmd_arg -d --default  -- W_DEFAULT  "default" "Example option w/ argument"
  cmd_arg -n --nullable -- WO_DEFAULT "Example option argument w/o default"
  cmd_arg               -- POSITIONAL "Example positional argument"
}

quick_start() {
  echo "Global binary option: $GLOBAL"
  echo "Option w/ default:    $W_DEFAULT"
  echo "Option w/o default:   $WO_DEFAULT"
  echo "Positional argument:  $POSITIONAL"
}

shifu_run quick_cmd "$@"
