#! /bin/bash

# Example shifu cli to partially reproduce similar functionality that
# the github cli, gh, provides. Wrapper around curl commands to the
# github rest api. Documentation:
# https://docs.github.com/en/rest?apiVersion=2022-11-28

. "${0%/*}"/shifu && shifu_less || exit 1

auth_file="$HOME/.sgh"

sgh_cmd() {
  cmd_name sgh
  cmd_subs auth_cmd issue_cmd pr_cmd
  cmd_help "Example github cli implemented with shifu"
}

auth_cmd() {
  cmd_name auth
  cmd_subs auth_clear_cmd auth_set_cmd
  cmd_help "Commands for interacting authentication tokens"
}

auth_set_cmd() {
  cmd_name set
  cmd_func auth_set
  cmd_help "Set token for authentication"

  cmd_argr PAT "Personal access token, documentation:
      https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens"
}

auth_set() {
  printf "$PAT" > "$auth_file"
}

auth_clear_cmd() {
  cmd_name clear
  cmd_func auth_clear
  cmd_help "Clear token for authentication"
}

auth_clear() {
  [ -f "$HOME/.sgh" ] && rm "$HOME/.sgh"
}

issue_cmd() {
  cmd_name issue
  cmd_subs issue_list_cmd issue_view_cmd
  cmd_help "Commands for interacting with github repository issues"

  cmd_optd :defer: -R --repo -- REPO "current repo" "Github repository in OWNER/REPO format"
}

issue_list_cmd() {
  cmd_name list
  cmd_func issue_list
  cmd_help "List issues in a GitHub repository"

  cmd_optd -s --state  -- STATE open "State of issue: open, closed, all"
  cmd_optd -n --number -- NUMBER 10 "Max number of results"
}

issue_list() {
  _resolve_repo
  _get_auth_token
  q_val="repo:$REPO+is:issue"
  [ "$STATE" != "all" ] && q_val="$q_val+state:$STATE"
  _update_query q "$q_val"
  _update_query per_page "$NUMBER"
  _gh_api_query "search/issues" | \
    jq -r '.items[] |
      "\(.created_at[5:7])/\(.created_at[8:10])/\(.created_at[0:4])" as $date |
      "#\(.number)  \(.state)  \(.title)  \(.user.login)  \($date)"'
}

issue_view_cmd() {
  cmd_name view
  cmd_func issue_view
  cmd_help "View issue in a GitHub repository"

  cmd_argr ISSUE_NUMBER "Issue number to view"
}

issue_view() {
  _resolve_repo
  _get_auth_token
  result=$(_gh_api_query "repos/$REPO/issues/$ISSUE_NUMBER" | \
    jq -M '
      "\(.title)
URL: \(.url)
State: \(.state)
Author: \(.user.login)
Body: \(.body)
"')
  printf "$result"
}

pr_cmd() {
  cmd_name pr
  cmd_subs pr_list_cmd pr_view_cmd
  cmd_help "Commands for interacting with github repository pull requests"

  cmd_optd :defer: -R --repo -- REPO "current repo" "Github repository in OWNER/REPO format"
}

pr_list_cmd() {
  cmd_name list
  cmd_func pr_list
  cmd_help "List pull requests in a GitHub repository"

  cmd_optd -s --state  -- STATE open "State of PR: open, closed, all"
  cmd_optd -n --number -- NUMBER 10  "Max number of results"
}

pr_list() {
  _resolve_repo
  _get_auth_token
  q_val="repo:$REPO+is:pr"
  [ "$STATE" != "all" ] && q_val="$q_val+state:$STATE"
  _update_query q "$q_val"
  _update_query per_page "$NUMBER"
  _gh_api_query "search/issues" | \
    jq -r '.items[] |
      "\(.created_at[5:7])/\(.created_at[8:10])/\(.created_at[0:4])" as $date |
      "#\(.number)  \(.state)  \(.title)  \(.user.login)  \($date)"'
}

pr_view_cmd() {
  cmd_name view
  cmd_func pr_view
  cmd_help "View pull request in a GitHub repository"

  cmd_argr PR_NUMBER "Pull request number to view"
}

pr_view() {
  _resolve_repo
  _get_auth_token
  _gh_api_query "repos/$REPO/pulls/$PR_NUMBER" | \
    jq -M '
      "\(.title)
URL: \(.issue_url)
State: \(.state)
Author: \(.user.login)
Body: \(.body)
"' | xargs printf
}

_resolve_repo() {
  [ "$REPO" != "current repo" ] && return
  origin_url=$(git config --get remote.origin.url)
  if [ "${origin_url}" != "${origin_url#https}" ]; then
    REPO="${origin_url#https://github.com/}"
  elif [ "${origin_url}" != "${origin_url#git}" ]; then
    REPO="${origin_url#git@github.com:}"
  else
    echo "Unknown repo url format: $origin_url"
    exit 1
  fi
  REPO="${REPO%.git}"
}

_update_query() {
  [ -z "$2" ] && return
  [ -z "$query" ] && query="?" || query="$query&"
  query="$query$1=$2"
}

_gh_api_query() {
  _gh_api "$1$query"
}

_gh_api() {
  curl_call="curl -sL \\
    -H \"Accept: application/vnd.github+json\" \\
    -H \"X-GitHub-Api-Version: 2022-11-28\""
  [ -n "$auth_token" ] && curl_call="$curl_call \\
    -H \"Authorization: Bearer $auth_token\""
  curl_call="$curl_call \\
    'https://api.github.com/$1'"
  eval "$curl_call"
}

_get_auth_token() {
  [ -f "$auth_file" ] && auth_token=$(cat "$auth_file")
  result=$(_gh_api)
  jq -e 'has("status") and .status != "200"' <<< "$result" > /dev/null
  if [ $? -eq 0 ]; then
    echo "$result" | jq -rM '.message'
    exit 1
  fi
}

shifu_run sgh_cmd "$@"
