#! /bin/sh

. "${0%/*}"/shifu && shifu_less || exit 1

tab_cmd() {
  cmd_name tab
  cmd_help "A tab completion shifu example"
  cmd_long "An example shifu cli demonstrating completions for
  * subcommand names
  * option names
  * option values with
    * enum completions
    * function completions
    * path completions"
  cmd_subs completion_cmd demo_cmd
}

completion_cmd() {
  cmd_name completion
  cmd_help "Main command with example options and tab completion capabilities"
  cmd_func no_op

  cmd_arg -e --enum -- ENUM_COMP enum_comp "Enum completion"
  cmd_arg_comp_enum magic value
  cmd_arg -f --func -- FUNC_COMP func_comp "Function completion, file extensions"
  cmd_arg_comp_func file_extension_completions
  cmd_arg           -- PATH_COMP "Path completion"
  cmd_arg_comp_path
}

file_extension_completions() {
  # dynamically complete with extenstions from files in current directory
  shifu_add_completions "$(ls -1 | grep '\.' | sed 's/.*\.//' | sort -u)"
}

demo_cmd() {
  cmd_name demo
  cmd_help "No-op command to show multiple subcommand completion options"
  cmd_func no_op
}

no_op() { :; }

shifu_run tab_cmd "$@"
